checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600
build:
    nodes:
        analysis:
            tests: { override: [php-scrutinizer-run] }
