<?php

/*
 * InterKassa driver for the Omnipay PHP payment processing library
 *
 * @link      https://github.com/hiqdev/omnipay-interkassa
 * @package   omnipay-interkassa
 * @license   MIT
 * @copyright Copyright (c) 2015, HiQDev (http://hiqdev.com/)
 */

namespace Omnipay\InterKassa\Message;

use Omnipay\Common\Exception\InvalidResponseException;
use Omnipay\Common\Message\RequestInterface;

/**
 * InterKassa Complete Purchase Response
 * Implements response for APIv1
 *
 * @package Omnipay\InterKassa\Message
 */
class OldCompletePurchaseResponse extends CompletePurchaseResponse
{
    /**
     * The checkout ID
     *
     * @return string
     */
    public function getCheckoutId()
    {
        return $this->data['ik_shop_id'];
    }

    /**
     * {@inheritdoc}
     */
    public function getSign()
    {
        return $this->data['ik_sign_hash'];
    }

    /**
     * The transaction identifier generated by the merchant website
     *
     * @return string
     */
    public function getTransactionId()
    {
        return $this->data['ik_trans_id'];
    }

    /**
     * {@inheritdoc}
     */
    public function getTransactionReference()
    {
        return $this->data['ik_payment_id'];
    }

    /**
     * The amount of payment
     *
     * @return mixed
     */
    public function getAmount()
    {
        return $this->data['ik_payment_amount'];
    }

    /**
     * The currency of the payment
     *
     * @return null currency is set
     */
    public function getCurrency()
    {
        return null;
    }

    /**
     * @inheritdoc
     */
    public function getPayer()
    {
        return $this->data['ik_paysystem_alias'];
    }

    /**
     * The time of request processing
     *
     * @return string
     */
    public function getTime()
    {
        return strtotime($this->data['ik_payment_timestamp'] . ' Europe/Moscow');
    }

    /**
     * The state of the payment.
     * Possible results:
     *  - `success`: the payment processed successfully
     *  - `fail`: the payment failed
     *
     * @return string
     * @see isSuccessful
     */
    public function getState()
    {
        return $this->data['ik_payment_state'];
    }
}
